THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp line=74 error=30 : unknown error
Traceback (most recent call last):
  File "main.py", line 86, in <module>
    train_data = batchify(corpus.train, args.batch_size)
  File "main.py", line 83, in batchify
    return data.to(device)
RuntimeError: cuda runtime error (30) : unknown error at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp:74
Traceback (most recent call last):
  File "generate.py", line 46, in <module>
    with open(args.checkpoint, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './modelusername0.pt'
